# https://help.github.com/en/categories/automating-your-workflow-with-github-actions
# https://github.com/php/pecl-database-dbase/blob/master/.github/workflows/ci.yml

on:
  - pull_request
  - push

name: "Continuous Integration"

jobs:

  linux:
    name: "Build and Tests (Linux)"

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        php: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: "Install liblzma"
        run: sudo apt-get install -y liblzma-dev

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP ${{ matrix.php }}"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: "Compile extension"
        run: |
          phpize
          ./configure
          make
          sudo make install

      - name: "Run tests"
        run: make test
