# https://help.github.com/en/categories/automating-your-workflow-with-github-actions
# https://github.com/php/pecl-database-dbase/blob/master/.github/workflows/ci.yml

on:
  - pull_request
  - push

name: "Continuous Integration"

jobs:

  linux:
    name: "Build and Tests (Linux)"

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        php: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: "Install liblzma"
        run: sudo apt-get install -y liblzma-dev

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP ${{ matrix.php }}"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: "Compile extension"
        run: |
          phpize
          ./configure
          make
          sudo make install

      - name: "Run tests"
        run: make test


  windows:
    name: "Build and Tests (Windows)"

    defaults:
      run:
        shell: cmd

    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019", "windows-2022"]
        php: ["8.1", "8.0"] # , "7.4", "7.3", "7.2", "7.1"
        arch: ["x64"] # , "x86"
        ts: ["ts"] # , "nts"
        exclude:
          - {os: "windows-2019", php: "8.1"}
          - {os: "windows-2019", php: "8.0"}
          - {os: "windows-2019", php: "7.4"}
          - {os: "windows-2019", php: "7.3"}
          - {os: "windows-2022", php: "7.2"}
          - {os: "windows-2022", php: "7.1"}

    runs-on: ${{matrix.os}}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP SDK ${{ matrix.php }}"
        uses: codemasher/setup-php-sdk@output-vs
        id: sdk
        with:
          version: ${{ matrix.php }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}
          deps: liblzma

      - name: "Enable Developer Command Prompt"
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          toolset: ${{ steps.sdk.outputs.toolset }}

      - name: "Compile extension"
        run: |
          phpize
          configure --enable-xz --with-prefix=${{ steps.sdk.outputs.prefix }}
          nmake
          nmake test
